/*
 * This file was generated by generate_typesystem.py.
 */
#ifndef __IAI_RESCUE_ROBOSHERLOCK_ALL_TYPES_H__
#define __IAI_RESCUE_ROBOSHERLOCK_ALL_TYPES_H__

#include <iai_rescue_robosherlock/types/type_definitions.h>


#endif /* __IAI_RESCUE_ROBOSHERLOCK_ALL_TYPES_H__ */
