/*
 * This file was generated by generate_typesystem.py.
 */
#ifndef __IAI_RESCUE_ROBOSHERLOCK_TYPE_DEFINITIONS_H__
#define __IAI_RESCUE_ROBOSHERLOCK_TYPE_DEFINITIONS_H__


#endif /* __IAI_RESCUE_ROBOSHERLOCK_TYPE_DEFINITIONS_H__ */
